### ISSUE TITLE
Can this ever work without Mapbox?

### ISSUE THREAD

**Issue by djasnowski** [christippett/leaflet-material#1]
I have a Leaflet map that uses a custom map. It does not use OpenMaps/Mapbox/etc. 

Can it work with only Leaflet?

**Comment by christippett** [comment]
Thanks for bringing this to my attention. It _should_ work with only Leaflet, but it doesn't. The library is throwing an error because it can't find `GeocoderControl` (a control that's only available to Mapbox).

I've noted the issue and will work on releasing a fix that will make the library work with Leaflet independent of any other dependencies. Expect an update in about a week or so.

**Comment by xSirrioNx** [comment]
@christippett, have you any news about this issue?

**Comment by christippett** [comment]
@xSirrioNx unfortunately I haven't had time to take another look at this. It's on the backburner for now. I'll happily review and accept a PR if you (or anyone else) wants to take a crack at it.

**Comment by rdelhommer** [comment]
Created a PR for this - https://github.com/christippett/leaflet-material/pull/4

It's just a bandaid solution that prevents creation of the geocoder control if mapbox isn't loaded.  I'm new to Leaflet, so I'm not entirely sure if anything more is needed.

**Comment by christippett** [comment]
@rdelhommer has provided a solution for getting around the Mapbox dependency and can now be used independently with only Leaflet.
